import type { Preset } from "./ComposedVariant";

// ============================================================
// Варианты лендинга, собираемые из набора блоков.
//
// ⚠️ ВО ВСЕХ ВАРИАНТАХ ВСЕ СЕМЬ СЕКЦИЙ лендинга: цифры, работы, страны,
// все семь отзывов, пять шагов, пять тарифов и призыв. Первая версия
// лаборатории их срезала — и сравнивала упрощение, а не дизайн
// (замечание владельца 21.09). Теперь отличается форма, порядок,
// шрифт, акцент и движение — но не наличие.
//
// У каждого указан СКИЛЛ-ИСТОЧНИК — какую линзу приложили к странице —
// и ЦЕНА: вариант, который нравится, нравится вместе со своим риском.
// ============================================================

/** Полный набор секций в порядке настоящего сайта. */
const SITE_ORDER = [
  "stats",
  "work",
  "countries",
  "reviews",
  "steps",
  "pricing",
  "cta",
] as const;

export const PRESETS: Preset[] = [
  {
    id: "hierarchy",
    label: "Иерархия",
    skill: "visual-hierarchy",
    idea: "Один громкий заголовок, одно действие; работы подняты на второе место, цифры строкой",
    risk: "Цифры уходят в мелкую строку — главный «социальный» аргумент теряет вес",
    kicker: "Minecraft build studio",
    headline: "One builder. Sixteen worlds.",
    sub: "Custom maps and structures, built by hand on commission.",
    hero: "left",
    font: "unbounded",
    accent: "orange",
    tone: "plain",
    density: "normal",
    scale: "loud",
    motion: "rise",
    sections: ["work", "stats", "reviews", "steps", "pricing", "countries", "cta"],
    work: "list",
    workCount: 4,
    statsShape: "inline",
    reviewsShape: "lead",
    stepsShape: "numbers",
    pricingShape: "rows",
    countriesShape: "inline",
    glow: true,
  },
  {
    id: "typescale",
    label: "Шкала шрифта",
    skill: "typography-scale",
    idea: "Модульная шкала на гротеске: огромный заголовок, спокойное тело, явные ступени",
    risk: "Крупный тип съедает первый экран на телефоне",
    kicker: "Since 2023",
    headline: "Worlds built by hand, not generated.",
    sub: "From a rough sketch to a place people want to walk through.",
    hero: "kicker",
    font: "grotesk",
    accent: "orange",
    tone: "plain",
    density: "airy",
    scale: "loud",
    motion: "rise",
    sections: [...SITE_ORDER],
    work: "list",
    workCount: 4,
    reviewsShape: "stack",
    stepsShape: "timeline",
    pricingShape: "rows",
    countriesShape: "grid",
  },
  {
    id: "spacing",
    label: "Воздух",
    skill: "spacing-system",
    idea: "Та же страница с удвоенным шагом отступов — проверка, сколько стоит тишина",
    risk: "Страница становится заметно длиннее, прокрутки больше",
    headline: "Space to look at the work",
    sub: "Custom Minecraft maps and structures, made to order.",
    hero: "centered",
    font: "grotesk",
    accent: "blue",
    tone: "plain",
    density: "airy",
    scale: "normal",
    motion: "fade",
    sections: [...SITE_ORDER],
    work: "grid",
    workCount: 3,
    reviewsShape: "lead",
    stepsShape: "cards",
    pricingShape: "cards",
    countriesShape: "marquee",
    glow: true,
  },
  {
    id: "dense",
    label: "Плотный",
    skill: "aesthetic-usability",
    idea: "Обратный эксперимент: всё сжато, карточки с рамками, максимум на экране сразу",
    risk: "Плотность читается как каталог, а не как студия",
    headline: "Sixteen builds. Pick one and look inside.",
    sub: "Maps, structures and full worlds, built on commission.",
    hero: "left",
    font: "grotesk",
    accent: "blue",
    tone: "plain",
    density: "tight",
    scale: "calm",
    motion: "none",
    sections: [...SITE_ORDER],
    work: "grid",
    workCount: 6,
    statsShape: "cards",
    reviewsShape: "grid",
    stepsShape: "cards",
    pricingShape: "cards",
    countriesShape: "grid",
  },
  {
    id: "tonal",
    label: "Тональный",
    skill: "color-system",
    idea: "Один цвет, три светлоты: секции отличаются тоном оранжевого, а не разными акцентами",
    risk: "Сайт становится «оранжевым», lime и blue теряют роль",
    kicker: "Built to order",
    headline: "Orange, all the way down",
    sub: "One accent, three tones — surfaces, not decorations.",
    hero: "left",
    font: "bricolage",
    accent: "orange",
    tone: "tonal",
    density: "normal",
    scale: "normal",
    motion: "rise",
    sections: [...SITE_ORDER],
    work: "bento",
    workCount: 5,
    reviewsShape: "marquee",
    stepsShape: "numbers",
    pricingShape: "bento",
    countriesShape: "marquee",
  },
  {
    id: "paper",
    label: "Бумага",
    skill: "color-system",
    idea: "Тёплая бумажная подложка и антиква — студия выглядит «старше» и дороже",
    risk: "Уходит от нашего #fbfbff и от Unbounded — то есть от узнаваемого вида сайта",
    headline: "Worlds worth printing",
    sub: "Hand-built Minecraft maps, commissioned and delivered.",
    hero: "split",
    font: "serif",
    accent: "orange",
    tone: "paper",
    density: "normal",
    scale: "normal",
    motion: "fade",
    sections: ["work", "reviews", "stats", "steps", "pricing", "countries", "cta"],
    work: "grid",
    workCount: 3,
    reviewsShape: "stack",
    stepsShape: "timeline",
    pricingShape: "rows",
    countriesShape: "inline",
  },
  {
    id: "dark",
    label: "Тёмный",
    skill: "dark-mode-design",
    idea: "Тёмная тема как основа, а не как переключатель: фотографии светятся на чёрном",
    risk: "Прямо спорит с решением 16.07 «тёмных секций на сайте нет»; навбар при этом светлый",
    kicker: "Minecraft build studio",
    headline: "Built in the dark, lit by the work",
    sub: "Custom maps and structures on commission.",
    hero: "left",
    font: "syne",
    accent: "lime",
    tone: "dark",
    density: "normal",
    scale: "normal",
    motion: "fade",
    sections: ["work", "stats", "reviews", "countries", "steps", "pricing", "cta"],
    work: "strip",
    statsShape: "inline",
    reviewsShape: "marquee",
    stepsShape: "timeline",
    pricingShape: "rows",
    countriesShape: "marquee",
  },
  {
    id: "bands",
    label: "Полосы",
    skill: "layout-grid",
    idea: "Секции чередуются фоном — страница читается как набор полос, а не как поток",
    risk: "Ритм полос спорит с длинными секциями: одна полоса может занять экран",
    headline: "Maps, made to order",
    sub: "Sixteen delivered builds and a marketplace of ready-made worlds.",
    hero: "centered",
    font: "unbounded",
    accent: "lime",
    tone: "bands",
    density: "normal",
    scale: "normal",
    motion: "stagger",
    sections: [...SITE_ORDER],
    work: "bento",
    workCount: 5,
    reviewsShape: "grid",
    stepsShape: "numbers",
    pricingShape: "bento",
    countriesShape: "grid",
    glow: true,
  },
  {
    id: "mobilefirst",
    label: "Телефон первым",
    skill: "responsive-design",
    idea: "Узкая колонка на любом экране: макет придуман для телефона, десктоп его не растягивает",
    risk: "На большом мониторе половина ширины пустует",
    headline: "Read it on the phone you're holding",
    sub: "Same page, one column, no desktop-only layer.",
    hero: "column",
    font: "bricolage",
    accent: "blue",
    tone: "plain",
    density: "normal",
    scale: "normal",
    motion: "rise",
    sections: [...SITE_ORDER],
    work: "single",
    statsShape: "inline",
    reviewsShape: "stack",
    stepsShape: "timeline",
    pricingShape: "rows",
    countriesShape: "inline",
  },
  {
    id: "aos",
    label: "Появление",
    skill: "scroll-reveal-libraries",
    idea: "Каждый блок проявляется при прокрутке — приём AOS, на нашем Motion",
    risk: "Когда появляется всё, не выделено ничего",
    headline: "Everything arrives as you scroll",
    sub: "Custom Minecraft maps and structures, built by hand.",
    hero: "centered",
    font: "unbounded",
    accent: "orange",
    tone: "plain",
    density: "normal",
    scale: "normal",
    motion: "scale",
    sections: [...SITE_ORDER],
    work: "grid",
    reviewsShape: "grid",
    stepsShape: "cards",
    pricingShape: "bento",
    countriesShape: "grid",
    glow: true,
  },
  {
    id: "still",
    label: "Без движения",
    skill: "animation-principles",
    idea: "Контрольный вариант: ни одной анимации. Нужен, чтобы понять, что движение вообще даёт",
    risk: "Никакого — это точка отсчёта для всех остальных",
    headline: "No motion at all",
    sub: "The same page, standing still. Compare it with the rest.",
    hero: "left",
    font: "unbounded",
    accent: "orange",
    tone: "plain",
    density: "normal",
    scale: "normal",
    motion: "none",
    sections: [...SITE_ORDER],
    work: "grid",
    reviewsShape: "grid",
    stepsShape: "cards",
    pricingShape: "bento",
    countriesShape: "grid",
  },
  {
    id: "feel",
    label: "По-человечески",
    skill: "interfaces-that-feel",
    idea: "Текст от первого лица, отзывы подняты вверх — страница говорит, а не докладывает",
    risk: "Личный тон сложнее масштабировать, когда авторов станет больше",
    headline: "I build the place you describe",
    sub: "Tell me the idea. I'll send sketches, then blocks.",
    hero: "split",
    font: "bricolage",
    accent: "lime",
    tone: "plain",
    density: "airy",
    scale: "normal",
    motion: "rise",
    sections: ["reviews", "work", "steps", "stats", "countries", "pricing", "cta"],
    work: "strip",
    reviewsShape: "lead",
    stepsShape: "timeline",
    pricingShape: "cards",
    countriesShape: "marquee",
  },
  {
    id: "market",
    label: "Магазин",
    skill: "visual-hierarchy",
    idea: "Первым делом тарифы библиотеки и работы, заказ — после: подписка важнее портфолио",
    risk: "Пока Stripe в тесте, главный путь ведёт туда, где нельзя заплатить",
    kicker: "Ready to download",
    headline: "Maps you can have today",
    sub: "Finished worlds, delivered as a file. Or commission your own.",
    hero: "left",
    font: "syne",
    accent: "orange",
    tone: "bands",
    density: "normal",
    scale: "normal",
    motion: "stagger",
    sections: ["pricing", "work", "stats", "reviews", "steps", "countries", "cta"],
    work: "grid",
    workCount: 6,
    statsShape: "inline",
    reviewsShape: "marquee",
    stepsShape: "numbers",
    pricingShape: "cards",
    countriesShape: "inline",
  },
];
