import type { Preset } from "./ComposedVariant";

// ============================================================
// Варианты лендинга, собираемые из набора блоков.
//
// У каждого указан СКИЛЛ-ИСТОЧНИК: какую линзу мы к странице
// приложили. Это главное в списке — не «двадцать макетов», а двадцать
// РАЗНЫХ ВОПРОСОВ к одной странице:
//   «что если иерархия строгая?», «что если воздуха вдвое больше?»,
//   «что если движения нет вообще?».
//
// ⚠️ У каждого есть цена, и она написана рядом. Вариант, который
// нравится, нравится вместе со своим риском.
// ============================================================

export const PRESETS: Preset[] = [
  {
    id: "hierarchy",
    label: "Иерархия",
    skill: "visual-hierarchy",
    idea: "Один громкий заголовок, одно действие, всё остальное понижено в ранге",
    risk: "Цифры и работы уходят вниз — посетитель может не долистать",
    kicker: "Minecraft build studio",
    headline: "One builder. Sixteen worlds.",
    sub: "Custom maps and structures, built by hand on commission.",
    hero: "left",
    tone: "plain",
    density: "normal",
    scale: "loud",
    motion: "rise",
    sections: ["work", "stats", "quote", "cta"],
    work: "list",
    statsShape: "inline",
    glow: true,
  },
  {
    id: "typescale",
    label: "Шкала шрифта",
    skill: "typography-scale",
    idea: "Модульная шкала: заголовок огромный, тело спокойное, между ними явные ступени",
    risk: "Крупный тип съедает первый экран на телефоне",
    headline: "Worlds built by hand, not generated.",
    sub: "From a rough sketch to a place people want to walk through.",
    hero: "kicker",
    kicker: "Since 2023",
    tone: "plain",
    density: "airy",
    scale: "loud",
    motion: "rise",
    sections: ["work", "quote", "stats", "cta"],
    work: "list",
    workCount: 4,
  },
  {
    id: "spacing",
    label: "Воздух",
    skill: "spacing-system",
    idea: "Та же страница с удвоенным шагом отступов — проверка, сколько стоит тишина",
    risk: "Страница становится заметно длиннее, прокрутки больше",
    headline: "Space to look at the work",
    sub: "Custom Minecraft maps and structures, made to order.",
    hero: "centered",
    tone: "plain",
    density: "airy",
    scale: "normal",
    motion: "fade",
    sections: ["stats", "work", "quote", "cta"],
    work: "grid",
    workCount: 3,
    glow: true,
  },
  {
    id: "dense",
    label: "Плотный",
    skill: "aesthetic-usability",
    idea: "Обратный эксперимент: всё сжато, карточки с рамками, много на экране сразу",
    risk: "Плотность читается как каталог, а не как студия",
    headline: "Sixteen builds. Pick one and look inside.",
    sub: "Maps, structures and full worlds, built on commission.",
    hero: "left",
    tone: "plain",
    density: "tight",
    scale: "calm",
    motion: "none",
    sections: ["stats", "work", "quote", "cta"],
    work: "grid",
    workCount: 6,
    statsShape: "cards",
    quoteShape: "card",
  },
  {
    id: "tonal",
    label: "Тональный",
    skill: "color-system",
    idea: "Один цвет, три светлоты: секции отличаются тоном оранжевого, а не разными акцентами",
    risk: "Сайт становится «оранжевым», lime и blue теряют роль",
    kicker: "Built to order",
    headline: "Orange, all the way down",
    sub: "One accent, three tones — surfaces, not decorations.",
    hero: "left",
    tone: "tonal",
    density: "normal",
    scale: "normal",
    motion: "rise",
    sections: ["stats", "work", "quote", "cta"],
    work: "bento",
    workCount: 5,
  },
  {
    id: "paper",
    label: "Бумага",
    skill: "color-system",
    idea: "Тёплая бумажная подложка вместо белого — фотографии на ней читаются мягче",
    risk: "Уходит от нашего #fbfbff, то есть от узнаваемого фона сайта",
    headline: "Worlds worth printing",
    sub: "Hand-built Minecraft maps, commissioned and delivered.",
    hero: "split",
    tone: "paper",
    density: "normal",
    scale: "normal",
    motion: "fade",
    sections: ["work", "quote", "stats", "cta"],
    work: "grid",
    workCount: 3,
  },
  {
    id: "dark",
    label: "Тёмный",
    skill: "dark-mode-design",
    idea: "Тёмная тема как основа, а не как переключатель: фотографии светятся на чёрном",
    risk: "Прямо спорит с решением 16.07 «тёмных секций на сайте нет»",
    kicker: "Minecraft build studio",
    headline: "Built in the dark, lit by the work",
    sub: "Custom maps and structures on commission.",
    hero: "left",
    tone: "dark",
    density: "normal",
    scale: "normal",
    motion: "fade",
    sections: ["work", "stats", "quote", "cta"],
    work: "strip",
    statsShape: "inline",
  },
  {
    id: "bands",
    label: "Полосы",
    skill: "layout-grid",
    idea: "Секции чередуются фоном — страница читается как набор полос, а не как поток",
    risk: "Ритм полос спорит с длинными секциями: одна полоса может занять экран",
    headline: "Maps, made to order",
    sub: "Sixteen delivered builds and a marketplace of ready-made worlds.",
    hero: "centered",
    tone: "bands",
    density: "normal",
    scale: "normal",
    motion: "stagger",
    sections: ["stats", "work", "quote", "cta"],
    work: "bento",
    workCount: 5,
    glow: true,
  },
  {
    id: "mobilefirst",
    label: "Телефон первым",
    skill: "responsive-design",
    idea: "Узкая колонка на любом экране: макет придуман для телефона, десктоп его не растягивает",
    risk: "На большом мониторе половина ширины пустует",
    headline: "Read it on the phone you're holding",
    sub: "Same page, one column, no desktop-only layer.",
    hero: "column",
    tone: "plain",
    density: "normal",
    scale: "normal",
    motion: "rise",
    sections: ["work", "stats", "quote", "cta"],
    work: "single",
  },
  {
    id: "aos",
    label: "Появление",
    skill: "scroll-reveal-libraries",
    idea: "Каждый блок проявляется при прокрутке — приём AOS, но на нашем Motion",
    risk: "Когда появляется всё, не выделено ничего",
    headline: "Everything arrives as you scroll",
    sub: "Custom Minecraft maps and structures, built by hand.",
    hero: "centered",
    tone: "plain",
    density: "normal",
    scale: "normal",
    motion: "fade",
    sections: ["stats", "work", "quote", "cta"],
    work: "grid",
    glow: true,
  },
  {
    id: "still",
    label: "Без движения",
    skill: "animation-principles",
    idea: "Контрольный вариант: ни одной анимации. Нужен, чтобы понять, что движение вообще даёт",
    risk: "Никакого — это точка отсчёта для всех остальных",
    headline: "No motion at all",
    sub: "The same page, standing still. Compare it with the rest.",
    hero: "left",
    tone: "plain",
    density: "normal",
    scale: "normal",
    motion: "none",
    sections: ["stats", "work", "quote", "cta"],
    work: "grid",
  },
  {
    id: "feel",
    label: "По-человечески",
    skill: "interfaces-that-feel",
    idea: "Текст от первого лица, отзыв крупной цитатой — страница говорит, а не докладывает",
    risk: "Личный тон сложнее масштабировать, когда авторов станет больше",
    headline: "I build the place you describe",
    sub: "Tell me the idea. I'll send sketches, then blocks.",
    hero: "split",
    tone: "plain",
    density: "airy",
    scale: "normal",
    motion: "rise",
    sections: ["quote", "work", "stats", "cta"],
    work: "strip",
  },
  {
    id: "market",
    label: "Магазин",
    skill: "visual-hierarchy",
    idea: "Первым делом готовые карты, заказ — вторым: витрина важнее портфолио",
    risk: "Пока Stripe в тесте, главный путь ведёт туда, где нельзя купить",
    kicker: "Ready to download",
    headline: "Maps you can have today",
    sub: "Finished worlds, delivered as a file. Or commission your own.",
    hero: "left",
    tone: "bands",
    density: "normal",
    scale: "normal",
    motion: "stagger",
    sections: ["work", "stats", "quote", "cta"],
    work: "grid",
    workCount: 6,
    statsShape: "inline",
  },
];
